# path related variables
paths:
  raw_data_directory: "../data/raw_data/"
  processed_data_directory: "../data/processed_data/"
  model_data_directory: "../models/"

# data related variables
data:
  cols_to_use:
    - 'NAME_EDUCATION_TYPE'
    - 'REGION_RATING_CLIENT'
    - 'REG_REGION_NOT_LIVE_REGION'
    - 'REG_REGION_NOT_WORK_REGION'
    - 'LIVE_REGION_NOT_WORK_REGION'
    - 'AMT_DRAWINGS_ATM_CURRENT'
    - 'AMT_DRAWINGS_CURRENT'
    - 'AMT_DRAWINGS_OTHER_CURRENT'
    - 'AMT_DRAWINGS_POS_CURRENT'
    - 'CNT_DRAWINGS_ATM_CURRENT'
    - 'CNT_DRAWINGS_CURRENT'
    - 'CNT_DRAWINGS_OTHER_CURRENT'
    - 'CNT_DRAWINGS_POS_CURRENT'
    - 'SELLERPLACE_AREA'
    - 'NAME_SELLER_INDUSTRY'
    - 'RCHRG_FRQ'
    - 'TRD_ACC'
    - 'OFC_DOC_EXP'
    - 'GST_FIL_DEF'
    - 'SIM_CARD_FAIL'
    - 'TRUECALR_FLAG'
    - 'ECOM_SHOP_RETURN'
    - 'UTILITY_BIL'
    - 'REG_VEH_CHALLAN'
    - 'LINKEDIN_DATA'
    - 'REV_FRM_UBER/RAPIDO'
    - 'NO_OF_SMRT_CARD'
    - 'NO_TYPE_OF_ACC'
    - 'SK_ID_CURR'
    - 'TARGET'
  id: "SK_ID_CURR"
  target: "TARGET"
  numerical_final:
    - 'REGION_RATING_CLIENT_min'
    - 'REGION_RATING_CLIENT_max'
    - 'REGION_RATING_CLIENT_mean'
    - 'REGION_RATING_CLIENT_sum'
    - 'REGION_RATING_CLIENT_std'
    - 'REG_REGION_NOT_LIVE_REGION_min'
    - 'REG_REGION_NOT_LIVE_REGION_max'
    - 'REG_REGION_NOT_LIVE_REGION_mean'
    - 'REG_REGION_NOT_LIVE_REGION_sum'
    - 'REG_REGION_NOT_LIVE_REGION_std'
    - 'REG_REGION_NOT_WORK_REGION_min'
    - 'REG_REGION_NOT_WORK_REGION_max'
    - 'REG_REGION_NOT_WORK_REGION_mean'
    - 'REG_REGION_NOT_WORK_REGION_sum'
    - 'REG_REGION_NOT_WORK_REGION_std'
    - 'LIVE_REGION_NOT_WORK_REGION_min'
    - 'LIVE_REGION_NOT_WORK_REGION_max'
    - 'LIVE_REGION_NOT_WORK_REGION_mean'
    - 'LIVE_REGION_NOT_WORK_REGION_sum'
    - 'LIVE_REGION_NOT_WORK_REGION_std'
    - 'AMT_DRAWINGS_ATM_CURRENT_min'
    - 'AMT_DRAWINGS_ATM_CURRENT_max'
    - 'AMT_DRAWINGS_ATM_CURRENT_mean'
    - 'AMT_DRAWINGS_ATM_CURRENT_sum'
    - 'AMT_DRAWINGS_ATM_CURRENT_std'
    - 'AMT_DRAWINGS_CURRENT_min'
    - 'AMT_DRAWINGS_CURRENT_max'
    - 'AMT_DRAWINGS_CURRENT_mean'
    - 'AMT_DRAWINGS_CURRENT_sum'
    - 'AMT_DRAWINGS_CURRENT_std'
    - 'AMT_DRAWINGS_OTHER_CURRENT_min'
    - 'AMT_DRAWINGS_OTHER_CURRENT_max'
    - 'AMT_DRAWINGS_OTHER_CURRENT_mean'
    - 'AMT_DRAWINGS_OTHER_CURRENT_sum'
    - 'AMT_DRAWINGS_OTHER_CURRENT_std'
    - 'AMT_DRAWINGS_POS_CURRENT_min'
    - 'AMT_DRAWINGS_POS_CURRENT_max'
    - 'AMT_DRAWINGS_POS_CURRENT_mean'
    - 'AMT_DRAWINGS_POS_CURRENT_sum'
    - 'AMT_DRAWINGS_POS_CURRENT_std'
    - 'CNT_DRAWINGS_ATM_CURRENT_min'
    - 'CNT_DRAWINGS_ATM_CURRENT_max'
    - 'CNT_DRAWINGS_ATM_CURRENT_mean'
    - 'CNT_DRAWINGS_ATM_CURRENT_sum'
    - 'CNT_DRAWINGS_ATM_CURRENT_std'
    - 'CNT_DRAWINGS_CURRENT_min'
    - 'CNT_DRAWINGS_CURRENT_max'
    - 'CNT_DRAWINGS_CURRENT_mean'
    - 'CNT_DRAWINGS_CURRENT_sum'
    - 'CNT_DRAWINGS_CURRENT_std'
    - 'CNT_DRAWINGS_OTHER_CURRENT_min'
    - 'CNT_DRAWINGS_OTHER_CURRENT_max'
    - 'CNT_DRAWINGS_OTHER_CURRENT_mean'
    - 'CNT_DRAWINGS_OTHER_CURRENT_sum'
    - 'CNT_DRAWINGS_OTHER_CURRENT_std'
    - 'CNT_DRAWINGS_POS_CURRENT_min'
    - 'CNT_DRAWINGS_POS_CURRENT_max'
    - 'CNT_DRAWINGS_POS_CURRENT_mean'
    - 'CNT_DRAWINGS_POS_CURRENT_sum'
    - 'CNT_DRAWINGS_POS_CURRENT_std'
    - 'SELLERPLACE_AREA_min'
    - 'SELLERPLACE_AREA_max'
    - 'SELLERPLACE_AREA_mean'
    - 'SELLERPLACE_AREA_sum'
    - 'SELLERPLACE_AREA_std'
    - 'NAME_EDUCATION_TYPE_count'
    - 'NAME_EDUCATION_TYPE_nunique'
    - 'NAME_SELLER_INDUSTRY_count'
    - 'NAME_SELLER_INDUSTRY_nunique'
    - 'RCHRG_FRQ'
    - 'TRD_ACC'
    - 'REV_FRM_CNSMR_APPS'
    - 'NO_OF_SMRT_CARD'
    - 'NO_TYPE_OF_ACC'
    - 'OFC_DOC_EXP'
    - 'GST_FIL_DEF'
    - 'REG_VEH_CHALLAN'
    - 'SIM_CARD_FAIL'
    - 'ECOM_SHOP_RETURN'
    - 'UTILITY_BIL'
    - 'LINKEDIN_DATA'
  numerical_fabricated:
    - 'REGION_RATING_CLIENT'
    - 'REG_REGION_NOT_LIVE_REGION'
    - 'REG_REGION_NOT_WORK_REGION'
    - 'LIVE_REGION_NOT_WORK_REGION'
    - 'AMT_DRAWINGS_ATM_CURRENT'
    - 'AMT_DRAWINGS_CURRENT'
    - 'AMT_DRAWINGS_OTHER_CURRENT'
    - 'AMT_DRAWINGS_POS_CURRENT'
    - 'CNT_DRAWINGS_ATM_CURRENT'
    - 'CNT_DRAWINGS_CURRENT'
    - 'CNT_DRAWINGS_OTHER_CURRENT'
    - 'CNT_DRAWINGS_POS_CURRENT'
    - 'SELLERPLACE_AREA'
    - 'RCHRG_FRQ'
    - 'TRD_ACC'
    - 'OFC_DOC_EXP'
    - 'GST_FIL_DEF'
    - 'SIM_CARD_FAIL'
    - 'ECOM_SHOP_RETURN'
    - 'UTILITY_BIL'
    - 'REG_VEH_CHALLAN'
    - 'LINKEDIN_DATA'
    - 'REV_FRM_UBER/RAPIDO'
    - 'NO_OF_SMRT_CARD'
    - 'NO_TYPE_OF_ACC'
  numerical_pre_existing:
    - 'REGION_RATING_CLIENT'
    - 'REG_REGION_NOT_LIVE_REGION'
    - 'REG_REGION_NOT_WORK_REGION'
    - 'LIVE_REGION_NOT_WORK_REGION'
    - 'AMT_DRAWINGS_ATM_CURRENT'
    - 'AMT_DRAWINGS_CURRENT'
    - 'AMT_DRAWINGS_OTHER_CURRENT'
    - 'AMT_DRAWINGS_POS_CURRENT'
    - 'CNT_DRAWINGS_ATM_CURRENT'
    - 'CNT_DRAWINGS_CURRENT'
    - 'CNT_DRAWINGS_OTHER_CURRENT'
    - 'CNT_DRAWINGS_POS_CURRENT'
    - 'SELLERPLACE_AREA'
  categorical_final:
    - 'NAME_EDUCATION_TYPE_mode'
    - 'NAME_SELLER_INDUSTRY_mode'
    - 'TRUECALR_FLAG'
  categorical_fabricated:
    - 'NAME_EDUCATION_TYPE'
    - 'NAME_SELLER_INDUSTRY'
    - 'TRUECALR_FLAG'
  categorical_pre_existing:
    - 'NAME_EDUCATION_TYPE'
    - 'NAME_SELLER_INDUSTRY'
  drop_cols:
    - 'TRUECALR_FLAG_Blue'
    - 'TRUECALR_FLAG_Golden'
    - 'TRUECALR_FLAG_Red'
    - 'RCHRG_FRQ'
    - 'TRD_ACC'
    - 'REV_FRM_CNSMR_APPS'
    - 'NO_OF_SMRT_CARD'
    - 'NO_TYPE_OF_ACC'
    - 'OFC_DOC_EXP'
    - 'GST_FIL_DEF'
    - 'REG_VEH_CHALLAN'
    - 'SIM_CARD_FAIL'
    - 'ECOM_SHOP_RETURN'
    - 'UTILITY_BIL'
    - 'LINKEDIN_DATA'
    - 'SK_ID_CURR'
    - 'TARGET'

  zero_to_one_ratio: 11.3874

files:
  junk_files:
    - 'HomeCredit_columns_description.csv'
    - 'application_test.csv'
    - 'bureau.csv'
    - 'bureau_balance.csv'
    - 'installments_payments.csv'
    - 'POS_CASH_balance.csv'
    - 'sample_submission.csv'

model: 'lightgbm_model.joblib'
threshold: 0.75