# path related variables
paths:
  raw_data_directory: "../data/raw_data/"
  processed_data_directory: "../data/processed_data/"
  model_data_directory: "../models/"

# data related variables
data:
  cols_to_use:
    - 'NAME_EDUCATION_TYPE'
    - 'REGION_RATING_CLIENT'
    - 'REG_REGION_NOT_LIVE_REGION'
    - 'REG_REGION_NOT_WORK_REGION'
    - 'LIVE_REGION_NOT_WORK_REGION'
    - 'AMT_DRAWINGS_ATM_CURRENT'
    - 'AMT_DRAWINGS_CURRENT'
    - 'AMT_DRAWINGS_OTHER_CURRENT'
    - 'AMT_DRAWINGS_POS_CURRENT'
    - 'CNT_DRAWINGS_ATM_CURRENT'
    - 'CNT_DRAWINGS_CURRENT'
    - 'CNT_DRAWINGS_OTHER_CURRENT'
    - 'CNT_DRAWINGS_POS_CURRENT'
    - 'SELLERPLACE_AREA'
    - 'NAME_SELLER_INDUSTRY'
    - 'RCHRG_FRQ'
    - 'TRD_ACC'
    - 'OFC_DOC_EXP'
    - 'GST_FIL_DEF'
    - 'SIM_CARD_FAIL'
    - 'TRUECALR_FLAG'
    - 'ECOM_SHOP_RETURN'
    - 'UTILITY_BIL'
    - 'REG_VEH_CHALLAN'
    - 'LINKEDIN_DATA'
    - 'REV_FRM_UBER/RAPIDO'
    - 'NO_OF_SMRT_CARD'
    - 'NO_TYPE_OF_ACC'
    - 'SK_ID_CURR'
    - 'TARGET'
  id: "SK_ID_CURR"
  target: "TARGET"
  numerical_fabricated:
    - 'REGION_RATING_CLIENT'
    - 'REG_REGION_NOT_LIVE_REGION'
    - 'REG_REGION_NOT_WORK_REGION'
    - 'LIVE_REGION_NOT_WORK_REGION'
    - 'AMT_DRAWINGS_ATM_CURRENT'
    - 'AMT_DRAWINGS_CURRENT'
    - 'AMT_DRAWINGS_OTHER_CURRENT'
    - 'AMT_DRAWINGS_POS_CURRENT'
    - 'CNT_DRAWINGS_ATM_CURRENT'
    - 'CNT_DRAWINGS_CURRENT'
    - 'CNT_DRAWINGS_OTHER_CURRENT'
    - 'CNT_DRAWINGS_POS_CURRENT'
    - 'SELLERPLACE_AREA'
    - 'RCHRG_FRQ'
    - 'TRD_ACC'
    - 'OFC_DOC_EXP'
    - 'GST_FIL_DEF'
    - 'SIM_CARD_FAIL'
    - 'ECOM_SHOP_RETURN'
    - 'UTILITY_BIL'
    - 'REG_VEH_CHALLAN'
    - 'LINKEDIN_DATA'
    - 'REV_FRM_UBER/RAPIDO'
    - 'NO_OF_SMRT_CARD'
    - 'NO_TYPE_OF_ACC'
    - 'TARGET'
  numerical_pre_existing:
    - 'REGION_RATING_CLIENT'
    - 'REG_REGION_NOT_LIVE_REGION'
    - 'REG_REGION_NOT_WORK_REGION'
    - 'LIVE_REGION_NOT_WORK_REGION'
    - 'AMT_DRAWINGS_ATM_CURRENT'
    - 'AMT_DRAWINGS_CURRENT'
    - 'AMT_DRAWINGS_OTHER_CURRENT'
    - 'AMT_DRAWINGS_POS_CURRENT'
    - 'CNT_DRAWINGS_ATM_CURRENT'
    - 'CNT_DRAWINGS_CURRENT'
    - 'CNT_DRAWINGS_OTHER_CURRENT'
    - 'CNT_DRAWINGS_POS_CURRENT'
    - 'SELLERPLACE_AREA'
    - 'TARGET'
  final_categorical_cols:
    -
  final_numerical_cols:
    -
  categorical_fabricated:
    - 'NAME_EDUCATION_TYPE'
    - 'NAME_SELLER_INDUSTRY'
    - 'TRUECALR_FLAG'
  categorical_pre_existing:
    - 'NAME_EDUCATION_TYPE'
    - 'NAME_SELLER_INDUSTRY'

files:
  junk_files:
    - 'HomeCredit_columns_description.csv'
    - 'application_test.csv'
    - 'bureau.csv'
    - 'bureau_balance.csv'
    - 'installments_payments.csv'
    - 'POS_CASH_balance.csv'
    - 'sample_submission.csv'